name: Free Ubuntu VPS

on:
  workflow_dispatch:   # Cho phép chạy thủ công
  push:                # Hoặc khi push code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up VPS
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install neofetch tmux tmate -y
          echo "VPS Ubuntu đã sẵn sàng!"
      - name: Start tmate session
        uses: mxschmitt/action-tmate@v3
