name: Ubuntu VPS

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cập nhật hệ thống
        run: sudo apt update -y

      - name: Tạo user & password
        run: |
          sudo useradd -m runner || true
          echo "runner:MyVps220" | sudo chpasswd
          sudo usermod -aG sudo runner

      - name: Cài Ngrok mới nhất
        run: |
          wget https://github.com/ngrok/ngrok/releases/latest/download/ngrok-linux-amd64.zip
          unzip ngrok-linux-amd64.zip
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Mở SSH Tunnel
        run: |
          ./ngrok tcp 22 > ngrok.log &
          sleep 10
          curl --retry 5 --retry-delay 3 --max-time 20 -s http://127.0.0.1:4040/api/tunnels > tunnels.json
          cat tunnels.json
