name: Ubuntu VPS SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cài đặt SSH
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server wget unzip
          sudo service ssh start

      - name: Tạo user & password
        run: |
          echo "runner:MyVps220" | sudo chpasswd

      - name: Cài Ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Mở SSH Tunnel
        run: |
          ./ngrok tcp 22 &
          sleep 10
          echo "==== SSH Login Info ===="
          curl --silent --show-error http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
          echo "User: runner"
          echo "Pass: MyVps220"
          sleep infinity
