name: Ubuntu VPS

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cập nhật hệ thống
        run: sudo apt update -y

      - name: Tạo user & password
        run: |
          sudo useradd -m runner || true
          echo "runner:MyVps220" | sudo chpasswd
          sudo usermod -aG sudo runner

      - name: Cài Ngrok mới nhất
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok -y
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Mở SSH Tunnel
        run: |
          nohup ngrok tcp 22 --log=stdout > ngrok.log &
          sleep 10
          curl --retry 5 --retry-delay 3 --max-time 20 -s http://127.0.0.1:4040/api/tunnels | jq
